### ISSUE TITLE
Implement error boundaries for meta projections

### ISSUE THREAD

**Issue by codingfabi** [codingfabi/hetpy#36]
Intercept the following error cases during meta projection creation: 

- [ ] specified meta path is not defined on the network schema. 
- [ ] no path instances of meta path were found.
- [ ] no nodes of source and sink type where found on the graph
